### PR TITLE
Update Spanner.md

### PR DESCRIPTION
**Pull request by xiang90**
To support replication, each spanserver implements a single Paxos state machine on top of each tablet. (An early Spanner incarnation supported multiple Paxos state machines per tablet, which allowed for more flexible replication configurations. The complexity of that de- sign led us to abandon it.) Each state machine stores its metadata and log in its corresponding tablet. Our Paxos implementation supports long-lived leaders with time-based leader leases, whose length defaults to 10 seconds. The current Spanner implementation logs ev- ery Paxos write twice: once in the tablet’s log, and once in the Paxos log. This choice was made out of expedi- ency, and we are likely to remedy this eventually. Our implementation of Paxos is pipelined, so as to improve Spanner’s throughput in the presence of WAN latencies; but writes are applied by Paxos in order (a fact on which we will depend in Section 4).
The Paxos state machines are used to implement a consistently replicated bag of mappings. The key-value mapping state of each replica is stored in its correspond- ing tablet. Writes must initiate the Paxos protocol at the leader; reads access state directly from the underlying tablet at any replica that is sufficiently up-to-date. The set of replicas is collectively a Paxos group.

### CODE REVIEW

**Comment by EasonLiao** [comment]
@xiang90 首先非常感谢你的翻译， 我有一些疑问， 之前论文提到一个spanner server会管理成百上千的tablet， 是否说明一个span server上会跑成千上百个Paxos instance?

**Comment by xiang90** [comment]
@EasonLiao 是的。也就是说一个server中会跑着很多paxos instance。这也涉及到了一些消息合并、分组的问题。

**Comment by xiang90** [comment]
@EasonLiao You might also interest in http://www.cockroachlabs.com/blog/scaling-raft/. This is a joint work of CoreOS etcd and CockroachDB teams. This is similar to what described in spanner.

**Comment by EasonLiao** [comment]
@xiang90  Thanks so much for your feedback! It's inspiring to read the blog post and the code. I like the abstraction that multinode maintains a group of raft instance and user only need to specify the group ID at their level. I'm still reading the code and it's enjoyable.

Thanks for your great work!

**Comment by xiang90** [comment]
@EasonLiao An early decision of etcd/raft is designed for clean API and testability. : )

**Comment by xiang90** [comment]
@ngaut All resolved. Merging.

**Pull request merged**
