### PR TITLE
spanner: 2.1

### PR DESCRIPTION
**Pull request by xiang90**
This section focuses on the spanserver implementation to illustrate how replication and distributed transactions have been layered onto our Bigtable-based implementa- tion. The software stack is shown in Figure 2. At the bottom, each spanserver is responsible for between 100 and 1000 instances of a data structure called a tablet. A tablet is similar to Bigtable’s tablet abstraction, in that it implements a bag of the following mappings:
(key:string, timestamp:int64) → string
Unlike Bigtable, Spanner assigns timestamps to data, which is an important way in which Spanner is more like a multi-version database than a key-value store. A tablet’s state is stored in set of B-tree-like files and a write-ahead log, all on a distributed file system called Colossus (the successor to the Google File System [15]).

### CODE REVIEW

**Comment by NormanOu** [comment]
ok

**Comment by xiang90** [comment]
@NormanOu Probably you can read through the paper first and start to translate from section 5.

**Comment by xiang90** [comment]
@ngaut Updated. Merging. I will try to resolve the comparison (cockroach vs spanner) and unit conflicts (fragment vs directory) later.

**Pull request merged**
